# Generated by Django 5.0.4 on 2024-05-13 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passactivity',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='passactivity',
            name='activity_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.acitivity'),
            preserve_default=False,
        ),
    ]
