# Generated by Django 5.0.4 on 2024-05-13 01:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_acitivity_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('posted', models.DateTimeField(default=datetime.datetime(2024, 5, 13, 1, 42, 48, 712910, tzinfo=datetime.timezone.utc))),
                ('deadline', models.DateField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classroom')),
            ],
        ),
        migrations.AlterField(
            model_name='passactivity',
            name='activity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activity'),
        ),
        migrations.DeleteModel(
            name='Acitivity',
        ),
    ]
