# Generated by Django 5.0.4 on 2024-05-13 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activity_alter_passactivity_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 10, 27, 38, 257362, tzinfo=datetime.timezone.utc)),
        ),
    ]
