# Generated by Django 5.0.4 on 2024-05-15 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_lesson_classroom_lesson_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 10, 16, 35, 384530, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 10, 16, 35, 384530, tzinfo=datetime.timezone.utc)),
        ),
    ]
